# Порт, на котором Redis будет принимать соединения
port 9000

# Уходить в фон
daemonize yes

# Отключаем защищённый режим — Redis будет принимать подключения откуда угодно.
# ВНИМАНИЕ: опасно в публичных сетях! Лучше использовать только в приватной сети
protected-mode no

# Директория для хранения данных (например, дампов RDB).
dir data
