notify_consumer:
	poetry run python3 notify_consumer.py

cheque_consumer:
	poetry run python3 cheque_consumer.py

warehouse_consumer:
	poetry run python3 warehouse_consumer.py

main_service:
	poetry run uvicorn main_service:app --reload