[tool.poetry]
package-mode=false

[tool.poetry.dependencies]
python = "^3.12"
redis = "^5.2.1"
pydantic = "^2.10.6"
pydantic-settings = "^2.7.1"
sqlalchemy = "^2.0.37"
fastapi = {extras = ["uvicorn"], version = "^0.115.7"}
uvicorn = "^0.34.0"
aiosqlite = "^0.20.0"
