lists_producer:
	poetry run python3 producer_lists.py

lists_consumer:
	poetry run python3 consumer_lists.py

streams_producer:
	poetry run python3 producer_streams.py

streams_consumer:
	poetry run python3 consumer_streams.py

pubsub_producer:
	poetry run python3 producer_pubsub.py

pubsub_consumer:
	poetry run python3 consumer_pubsub.py

fallback_producer:
	poetry run python3 producer_lists_fallback.py

fallback_consumer:
	poetry run python3 consumer_lists_fallback.py
	