[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
redis = "^5.2.1"
fastapi = "^0.115.7"
sqlalchemy = "^2.0.37"
uvicorn = "^0.34.0"
pydantic-settings = "^2.7.1"
aiosqlite = "^0.20.0"
faker = "^35.2.0"
passlib = "^1.7.4"

